# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('sujet', models.CharField(choices=[('edelia', "Histoire d'Edelia"), ('isep', "Background des membres de l'Isep")], default='edelia', max_length=10)),
                ('histoire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
