# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetes', '0004_auto_20161211_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quete',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
