# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetes', '0005_auto_20161211_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quete',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
