# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_possession_perso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possession',
            name='item',
        ),
        migrations.DeleteModel(
            name='Possession',
        ),
    ]
