# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profil_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
