# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheperso',
            name='PO',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='descriptif',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='items',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='sorts',
        ),
        migrations.RemoveField(
            model_name='ficheperso',
            name='traits',
        ),
    ]
