# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0002_auto_20161204_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheperso',
            name='PO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='mana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='sorts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='traits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
