# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0003_auto_20161204_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagesPerso/'),
        ),
    ]
