# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import personnages.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0004_perso_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=personnages.models.renommage),
        ),
    ]
