# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import personnages.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0006_auto_20161204_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheperso',
            name='PO',
        ),
        migrations.AddField(
            model_name='ficheperso',
            name='po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=personnages.models.renommage),
        ),
    ]
