# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0008_auto_20161210_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheperso',
            name='extra',
            field=models.URLField(blank=True, null=True),
        ),
    ]
