# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0011_ficheperso_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheperso',
            name='etat',
            field=models.CharField(choices=[('EnVie', 'En vie'), ('Mort', 'Mort'), ('Disparu', 'Disparu')], default='EnVie', max_length=20),
        ),
    ]
