# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnages', '0012_ficheperso_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheperso',
            name='lvl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
